_target_: gaze_module.models.gaze_module.GazeModule

solver:
  name: "AdamW"
  momentum: 0.9
  lr: 0.001
  weight_decay: 0.005
  decay_steps: [10,20]
  decay_gamma: 0.1
  layer_decay: null
  warmup_epochs: 5
  scheduler: "cosine"
  apply_linear_scaling: True

net:
  _target_: gaze_module.models.gazetr.model.GazeTR
  pretrained: true

# compile model for faster training with pytorch 2.0
compile: false
output_path: ${paths.output_dir}
