_target_: gaze_module.models.gaze_module.GazeModule

solver:
  name: "AdamW"
  momentum: 0.9
  lr: 0.001
  weight_decay: 0.001
  decay_steps: [10,20]
  decay_gamma: 0.1
  layer_decay: null
  warmup_epochs: 5
  scheduler: "cosine"
  apply_linear_scaling: True

net:
  _target_: gaze_module.models.components.gaze_models.GazeNet
  encoder: ${extras.resenet18}
  head:
    _target_: gaze_module.models.components.gaze_models.HeadCartesian
    _partial_: true
  activation:
    _target_: torch.nn.ReLU

loss:
  # _target_: gaze_module.models.losses.GazeLoss
  # main: null
  #   #_target_: gaze_module.models.losses.AngularArcossLoss
  # add: 
  #   _target_: gaze_module.models.losses.PinBallLoss
  #   mode: ${model.mode_angular}
  _target_: gaze_module.models.losses.VMFDistributionLoss

mode_angular: cartesian

# compile model for faster training with pytorch 2.0
compile: false
output_path: ${paths.output_dir}


